### PR TITLE
CI: add a couple of plists

### PR DESCRIPTION
**Pull request by compnerd**
These will communicate information to swift-package-manager.

---
This change is [Reviewable](https://reviewable.io/reviews/compnerd/swift-build/287)

### CODE REVIEW

**Comment by lxbndr** [comment]
Just curious, what these plist do?

**Comment by compnerd** [comment]
The plist itself is just a storage mechanism.  It contains information relevant to the SDK/platform support (i.e. the XCTest version and the MSVC runtime in use).  This information is useful to external consumers (i.e. s-p-m).  They are intended to serve as a bridge to s-p-m to enable `swift build` to be used without any flags.

**Pull request merged**
